// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/24/2026, 10:19:52 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/User/Documents/code_pro/clavis_frontend/iwas-medical-scribe/components/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","C:/Users/User/Documents/code_pro/clavis_frontend/iwas-medical-scribe/components/global/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","C:/Users/User/Documents/code_pro/clavis_frontend/iwas-medical-scribe/components/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","C:/Users/User/Documents/code_pro/clavis_frontend/iwas-medical-scribe/layouts/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","C:/Users/User/Documents/code_pro/clavis_frontend/iwas-medical-scribe/plugins/**/*.{js,ts,mjs}","C:/Users/User/Documents/code_pro/clavis_frontend/iwas-medical-scribe/composables/**/*.{js,ts,mjs}","C:/Users/User/Documents/code_pro/clavis_frontend/iwas-medical-scribe/utils/**/*.{js,ts,mjs}","C:/Users/User/Documents/code_pro/clavis_frontend/iwas-medical-scribe/pages/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","C:/Users/User/Documents/code_pro/clavis_frontend/iwas-medical-scribe/{A,a}pp.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","C:/Users/User/Documents/code_pro/clavis_frontend/iwas-medical-scribe/{E,e}rror.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","C:/Users/User/Documents/code_pro/clavis_frontend/iwas-medical-scribe/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;