<script setup lang="ts">
import { computed, ref, onMounted } from 'vue'
import { Bell, Bot, ChevronDown, ChevronLeft, ChevronRight, FileText, FlaskConical, HelpCircle, Home, LayoutTemplate, Menu, Mic, Paperclip, Pill, Search, Send, Settings, Sun, UserRound, BarChart3, Sparkles, X } from 'lucide-vue-next'
import PatientModal from '~/components/dashboard/PatientModal.vue'
import NotificationsModal from '~/components/dashboard/NotificationsModal.vue'
import ModelsModal from '~/components/dashboard/ModelsModal.vue'
import StatsModal from '~/components/dashboard/StatsModal.vue'
import TemplatesModal from '~/components/dashboard/TemplatesModal.vue'
import ResourceSearchModal from '~/components/dashboard/ResourceSearchModal.vue'
import DocumentUploadModal from '~/components/dashboard/DocumentUploadModal.vue'

const api=useApi()
const leftCollapsed=ref(false), rightCollapsed=ref(false), mobileLeft=ref(false), activeModal=ref(''), profileOpen=ref(false)
const query=ref(''), message=ref(''), recording=ref(false), commonDiagnoses=ref<any[]>([]), diagnosisLoading=ref(true), diagnosisError=ref('')
const resourceModal=ref('')
const patient=ref<any>({name:'',age:'',gender:'',id:'',phone:'',allergies:[],conditions:[],last_visit:''})
const nav=[['Home',Home,''],['Patient',UserRound,'Identify & Manage'],['Notifications',Bell,'Alerts & Preferences'],['AI Models',Bot,'Select & Configure'],['Statistics',BarChart3,'Insights & Reports'],['Treatment Templates',LayoutTemplate,'Plan & Prescribe']]
const filtered=computed(()=>commonDiagnoses.value.filter(d=>(d.name||d.title||'').toLowerCase().includes(query.value.toLowerCase())))
async function loadCommonDiagnoses(){diagnosisLoading.value=true;diagnosisError.value='';try{commonDiagnoses.value=await api<any[]>('/diagnoses/common')}catch(e:any){diagnosisError.value=e?.data?.message||'Could not load common diagnoses.';commonDiagnoses.value=[]}finally{diagnosisLoading.value=false}}
onMounted(loadCommonDiagnoses)
function openNav(label:string){if(label==='Home')return;activeModal.value=label;mobileLeft.value=false}
function send(){if(!message.value.trim())return;message.value=''}
function selectPatient(p:any){patient.value={...patient.value,...p};activeModal.value=''}
</script>
<template>
<div class="min-h-screen bg-[#f8f9f7] text-[#172321] flex overflow-hidden">
  <div v-if="mobileLeft" class="fixed inset-0 z-40 bg-black/20 lg:hidden" @click="mobileLeft=false"></div>
  <aside :class="['sidebar',leftCollapsed?'sidebar-collapsed':'','mobile-sidebar',mobileLeft?'mobile-sidebar-open':'']">
    <div class="flex items-center justify-between px-2 mb-8"><div class="flex items-center gap-3 overflow-hidden"><div class="brand-mark"><span/><span/></div><div v-if="!leftCollapsed"><div class="text-[25px] leading-none font-semibold tracking-tight">Clavis</div><div class="text-sm text-slate-500 mt-1">Medical Scribe</div></div></div><button class="collapse-btn lg:flex" @click="leftCollapsed=!leftCollapsed"><ChevronLeft v-if="!leftCollapsed" :size="17"/><ChevronRight v-else :size="17"/></button><button class="collapse-btn lg:hidden" @click="mobileLeft=false"><X :size="17"/></button></div>
    <nav class="space-y-2"> <button v-for="[label,Icon,sub] in nav" :key="label" @click="openNav(label)" :class="['nav-item',activeModal===label?'nav-active':'']"><component :is="Icon" :size="21" :stroke-width="1.8"/><div v-if="!leftCollapsed" class="min-w-0"><div class="font-medium text-[14px]">{{label}}</div><div v-if="sub" class="text-[10px] mt-0.5 text-slate-500">{{sub}}</div></div></button></nav>
    <div class="mt-auto"><div class="border-t border-[#e5e8e6] pt-5 space-y-1"><button class="nav-item"><Settings :size="20"/><span v-if="!leftCollapsed">Settings</span></button><button class="nav-item"><HelpCircle :size="20"/><span v-if="!leftCollapsed">Help & Support</span></button></div><div v-if="!leftCollapsed" class="px-3 pt-7 pb-1"><div class="text-[17px] font-medium leading-tight">Less typing.<br/>More care.</div><div class="w-6 h-px bg-[#263b37] my-4"/><p class="text-xs leading-5 text-slate-500">Clavis helps you focus<br/>on what matters.</p></div></div>
  </aside>

  <main class="flex-1 min-w-0 h-screen overflow-auto px-3 py-3 sm:px-5 sm:py-4">
    <header class="h-[58px] flex items-center gap-2 sm:gap-4 mb-3"><button class="collapse-btn lg:hidden bg-white border" @click="mobileLeft=true"><Menu :size="19"/></button><div class="h-11 bg-white border border-[#e5e8e6] rounded-xl flex-1 flex items-center px-4 gap-3 shadow-[0_8px_28px_rgba(20,35,33,.045)]"><Search :size="19"/><input class="outline-none w-full text-sm placeholder:text-slate-400" placeholder="Search patients, notes, diagnosis, medications..."/></div><button class="hidden sm:flex w-11 h-11 rounded-full items-center justify-center hover:bg-white"><Sun :size="20"/></button><div class="relative"><button class="h-11 pl-1 pr-2 flex items-center gap-2 rounded-xl hover:bg-white" @click="profileOpen=!profileOpen"><div class="relative"><div class="w-10 h-10 rounded-full bg-[#d9e5e0] flex items-center justify-center font-semibold text-[#21403a]">AN</div><span class="absolute bottom-0 right-0 w-2.5 h-2.5 rounded-full bg-[#6e9c84] border-2 border-white"/></div><div class="hidden md:block leading-tight text-left"><div class="font-semibold text-[14px]">Dr. Arjun Nair</div><div class="text-[10px] text-slate-500 mt-1">General Medicine</div></div><ChevronDown :size="17"/></button><div v-if="profileOpen" class="absolute right-0 top-12 z-30 w-64 rounded-xl border border-[#e5e8e6] bg-white p-3 shadow-xl"><div class="p-3"><div class="font-semibold">Dr. Arjun Nair</div><div class="mt-1 text-xs text-slate-500">General Medicine</div><div class="mt-3 text-xs text-slate-500">Account details, clinic profile, subscription and sign out can be connected here.</div></div></div></div></header>

    <div :class="['dashboard-grid',rightCollapsed?'right-is-collapsed':'']">
      <section class="min-w-0">
        <div class="bg-white border border-[#e5e8e6] rounded-xl shadow-[0_8px_28px_rgba(20,35,33,.045)] px-4 sm:px-5 py-4 mb-3 flex items-center justify-between gap-3"><div class="flex items-center gap-3 min-w-0"><div class="w-12 h-12 sm:w-14 sm:h-14 shrink-0 rounded-full bg-[#e0edf5] flex items-center justify-center text-[#31627b] font-semibold">{{patient.name ? patient.name.slice(0,2).toUpperCase() : 'PT'}}</div><div class="min-w-0"><div class="text-lg sm:text-[21px] font-semibold tracking-tight truncate">{{patient.name||'No patient selected'}}</div><div class="text-[11px] text-slate-500 mt-1 truncate">{{patient.age||'—'}} years · {{patient.gender||'—'}} · ID: {{patient.id||'—'}} · {{patient.phone||'—'}}</div><div class="flex gap-2 mt-2 overflow-auto"><span v-for="c in patient.conditions" :key="c" class="px-2.5 py-1 rounded-full bg-[#f3f5f4] border border-[#e5e8e6] text-[9px] whitespace-nowrap">{{c}}</span><span v-for="a in patient.allergies" :key="a" class="px-2.5 py-1 rounded-full bg-[#fbf4ee] border border-[#eadfD5] text-[9px] whitespace-nowrap">Allergy: {{a}}</span></div></div></div><div class="hidden sm:flex gap-2 shrink-0"><button class="secondary-btn h-9 px-3 text-xs" @click="activeModal='Patient'">View / Change</button></div></div>
        <div class="bg-white border border-[#e5e8e6] rounded-xl shadow-[0_8px_28px_rgba(20,35,33,.045)] min-h-[calc(100vh-260px)] flex flex-col"><div class="flex-1 p-4 sm:p-7 space-y-5 overflow-auto"><div class="flex gap-3 max-w-[88%]"><div class="w-9 h-9 shrink-0 rounded-full bg-[#e7ecea] flex items-center justify-center"><Sparkles :size="16"/></div><div class="bg-[#f3f4f3] rounded-2xl rounded-tl-md p-4 text-sm leading-6"><p>Hello Dr. Arjun,</p><p class="mt-2">Select a patient and dictate, type, or upload information. I can help draft clinical notes and surface suggestions for review.</p><span class="block text-[10px] text-slate-400 mt-2">AI assistant</span></div></div><div class="flex justify-end"><div class="bg-[#e5ece8] rounded-2xl rounded-tr-md p-4 max-w-[82%] text-sm leading-6">Patient encounter details will appear here as you dictate or enter them. <span class="block text-[10px] text-slate-400 mt-2">Draft encounter</span></div></div></div><div class="px-3 sm:px-5 pb-4"><div class="flex gap-2"><button class="w-12 sm:w-14 h-12 sm:h-14 rounded-xl border border-[#e5e8e6] flex items-center justify-center" title="Upload document"><Paperclip :size="20"/></button><div class="flex-1 h-12 sm:h-14 rounded-xl border border-[#e5e8e6] flex items-center px-3 sm:px-4 bg-white"><input v-model="message" @keyup.enter="send" class="outline-none flex-1 text-sm placeholder:text-slate-400" placeholder="Type a message or start dictating..."/><button @click="send" class="w-10 h-10 rounded-lg bg-[#18312e] text-white flex items-center justify-center"><Send :size="18"/></button></div></div><div class="grid grid-cols-2 sm:grid-cols-5 gap-2 mt-3"><button class="utility" @click="resourceModal='document'"><FileText :size="21"/><b>Upload Document</b><span>Lab reports, images</span></button><button class="utility" @click="recording=!recording"><Mic :size="21"/><b>{{recording?'Stop Recording':'Start Recording'}}</b><span>Voice to note</span></button><button class="utility" @click="resourceModal='medicine'"><Pill :size="21"/><b>Search Medicines</b><span>Brand / Generic</span></button><button class="utility" @click="resourceModal='diagnosis'"><Search :size="21"/><b>Search Diagnosis</b><span>Available in area</span></button><button class="utility" @click="resourceModal='tests'"><FlaskConical :size="21"/><b>Order Tests</b><span>Lab / Imaging</span></button></div></div></div>
      </section>

      <aside v-if="!rightCollapsed" class="diagnosis-panel"><div class="flex items-center justify-between mb-3"><h2 class="text-[17px] font-semibold">Common Diagnosis</h2><button class="icon-btn" @click="rightCollapsed=true" title="Collapse panel"><ChevronRight :size="17"/></button></div><div class="search-field mb-3"><Search :size="16"/><input v-model="query" placeholder="Search diagnosis..."/></div><div v-if="diagnosisLoading" class="py-10 text-center text-xs text-slate-400">Loading diagnoses…</div><div v-else-if="diagnosisError" class="alert-error text-xs">{{diagnosisError}}</div><div v-else class="overflow-auto flex-1 pr-1"><button v-for="d in filtered" :key="d.id||d.code||d.name" class="diagnosis-row"><span>{{d.name||d.title}}</span><ChevronRight :size="15" class="text-slate-400 shrink-0"/></button><div v-if="!filtered.length" class="text-xs text-slate-400 p-3">No diagnosis found.</div></div></aside>
      <button v-else class="right-expand hidden lg:flex" @click="rightCollapsed=false"><ChevronLeft :size="18"/></button>
    </div>
  </main>

  <div v-if="activeModal==='Patient'"><PatientModal @close="activeModal=''" @select="selectPatient"/></div>
  <NotificationsModal v-if="activeModal==='Notifications'" @close="activeModal=''"/>
  <ModelsModal v-if="activeModal==='AI Models'" @close="activeModal=''"/>
  <StatsModal v-if="activeModal==='Statistics'" @close="activeModal=''"/>
  <TemplatesModal v-if="activeModal==='Treatment Templates'" @close="activeModal=''"/>
  <ResourceSearchModal v-if="resourceModal==='medicine'" title="Search Medicines" subtitle="Search your approved formulary or connected medicine database." endpoint="/medicines/search" placeholder="Medicine name, generic, brand…" @close="resourceModal=''"/>
  <ResourceSearchModal v-if="resourceModal==='diagnosis'" title="Search Diagnosis" subtitle="Find diagnosis options available in the configured clinical area." endpoint="/diagnoses/search" placeholder="Diagnosis, ICD code…" @close="resourceModal=''"/>
  <ResourceSearchModal v-if="resourceModal==='tests'" title="Search Tests" subtitle="Search connected laboratory and imaging services." endpoint="/tests/search" placeholder="Test, panel, imaging…" @close="resourceModal=''"/>
  <DocumentUploadModal v-if="resourceModal==='document'" @close="resourceModal=''"/>
</div>
</template>
